---
# https://taskfile.dev

version: "3"

includes:
  manual: ./misc/manual/task.yaml

  aws: ./tools/aws/task.yaml
  dotnet6: ./tools/dotnet/6/task.yaml
  dotnet7: ./tools/dotnet/7/task.yaml
  go1.20: ./tools/go/1.20/task.yaml
  go1.21: ./tools/go/1.21/task.yaml
  kubectl: ./tools/kubectl/task.yaml
  k3d: ./tools/k3d/task.yaml
  node: ./tools/node/task.yaml
  orbstack: ./tools/orbstack/task.yaml
  poetry: ./tools/poetry/task.yaml
  pulumi: ./tools/pulumi/task.yaml
  python: ./tools/python/task.yaml
  rancher: ./tools/rancher/task.yaml
  sops: ./tools/sops/task.yaml
  tilt: ./tools/tilt/task.yaml
  yamlfmt: ./tools/yamlfmt/task.yaml

tasks:
  default:
    cmds:
      - task --list
    silent: true

  # Node depends on nvm, which uses shell variables to modify the environment.
  # For this reason, it might be simpler to use the node:node and node:npm
  # tasks, rather than relying on users to setup their environment.
  node-run:
    desc: Run node
    silent: true
    cmds:
      - echo "Running node {{.CLI_ARGS}}"
      - task: node:node
        vars:
          ARGS: "{{.CLI_ARGS}}"

  npm-run:
    desc: Run npm
    silent: true
    cmds:
      - echo "Running node {{.CLI_ARGS}}"
      - task: node:npm
        vars:
          ARGS: "{{.CLI_ARGS}}"

  manual-secret:
    desc: Request user to manually enter a secret
    silent: true
    status:
      - grep "SECRET=.*" .env
    cmds:
      - task: manual:prompt_secret
        vars:
          INSTRUCTIONS: |
            What is the secret?
            1. Go to this super secret URL ...
            2. Copy the secret from the page.
            3. Enter it below.
          OUTPUT_FILE: ".env"
          OUTPUT_APPEND: true
          OUTPUT_TEMPLATE: "SECRET=$SECRET"
