---
# https://taskfile.dev

version: "3"

includes:
  aws: ./tools/aws/task.yaml
  dotnet6: ./tools/dotnet/6/task.yaml
  dotnet7: ./tools/dotnet/7/task.yaml
  go1.20: ./tools/go/1.20/task.yaml
  go1.21: ./tools/go/1.21/task.yaml
  kubectl: ./tools/kubectl/task.yaml
  k3d: ./tools/k3d/task.yaml
  node: ./tools/node/task.yaml
  orbstack: ./tools/orbstack/task.yaml
  poetry: ./tools/poetry/task.yaml
  pulumi: ./tools/pulumi/task.yaml
  python: ./tools/python/task.yaml
  rancher: ./tools/rancher/task.yaml
  sops: ./tools/sops/task.yaml
  tilt: ./tools/tilt/task.yaml
  yamlfmt: ./tools/yamlfmt/task.yaml

tasks:
  default:
    cmds:
      - task --list
    silent: true

  node-run:
    desc: Run node
    silent: true
    cmds:
      - echo "Running node {{.CLI_ARGS}}"
      - task: node:run
        vars:
          ARGS: "{{.CLI_ARGS}}"
