# https://taskfile.dev

version: "3"

includes:
  awscli: ./tools/awscli/task.yaml
  dotnet6: ./tools/dotnet/6/task.yaml
  dotnet7: ./tools/dotnet/7/task.yaml
  kubectl: ./tools/kubectl/task.yaml
  k3d: ./tools/k3d/task.yaml
  orbstack: ./tools/orbstack/task.yaml
  poetry: ./tools/poetry/task.yaml
  python: ./tools/python/task.yaml
  rancher: ./tools/rancher/task.yaml
  sops: ./tools/sops/task.yaml
  tilt: ./tools/tilt/task.yaml
  yamlfmt: ./tools/yamlfmt/task.yaml

tasks:
  default:
    cmds:
      - task --list
    silent: true
