---
name: YAML lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Install dependencies
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Format
        run: yamlfmt -lint .

